version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"  # Map FastAPI port
      - "8501:8501"  # Map Streamlit port
